package questions

import "ggame/backend/internal/models"

var bank = []models.Question{
	// ================== 9 КЛАСС ==================

	{ID: "q9-1", Grade: 9, Topic: "Логика шлюзов", Text: "Три шлюза A, B и C ведут к Кристаллу. Только один верный. Надписи:\nA: «Кристалл за этим шлюзом».\nB: «Кристалл не за шлюзом A».\nC: «Кристалл не за этим шлюзом».\nРовно одна надпись истинна. Где Кристалл?", Options: []string{"A", "B", "C"}, CorrectAnswer: 2, Explanation: "Если за C, истинна только B.", TimeLimitSeconds: 90, Difficulty: 2},
	{ID: "q9-2", Grade: 9, Topic: "Роботы-стражники", Text: "Два робота: один всегда правдив, другой всегда лжёт. Один сказал: «Мы оба лжём». Кто это сказал?", Options: []string{"Правдивый", "Лжец", "Невозможно определить"}, CorrectAnswer: 1, Explanation: "Правдивый не мог бы назвать себя лжецом.", TimeLimitSeconds: 60, Difficulty: 1},
	{ID: "q9-3", Grade: 9, Topic: "Код доступа", Text: "Код – три разные цифры. Сумма цифр 12. Первая цифра вдвое больше третьей. Вторая на 1 больше третьей. Найдите код.", Options: []string{"642", "462", "534", "354"}, CorrectAnswer: 0, Explanation: "x=2, тогда 6,4,2.", TimeLimitSeconds: 75, Difficulty: 2},
	{ID: "q9-4", Grade: 9, Topic: "Планета часов", Text: "Корабельные часы спешат на 5 минут каждый час. В 12:00 их выставили верно. Что покажут часы через 6 реальных часов?", Options: []string{"17:30", "18:00", "18:30", "19:00"}, CorrectAnswer: 2, Explanation: "Убегут на 30 минут.", TimeLimitSeconds: 60, Difficulty: 1},
	{ID: "q9-5", Grade: 9, Topic: "Ряд артефактов", Text: "Символы: △, ○, □, △, ○, □, △, ○, ?\nКакой символ следующий?", Options: []string{"△", "○", "□"}, CorrectAnswer: 2, Explanation: "Цикл из трёх фигур.", TimeLimitSeconds: 45, Difficulty: 1},
	{ID: "q9-6", Grade: 9, Topic: "Экипажи и планеты", Text: "«Орион», «Вега», «Сириус» сели на красную, синюю и зелёную планеты. Орион не на красной, Вега не на синей, Сириус не на зелёной, Вега на красной. Где Орион?", Options: []string{"Красная", "Синяя", "Зелёная"}, CorrectAnswer: 2, Explanation: "Вега=красная, Сириус=синяя, Орион=зелёная.", TimeLimitSeconds: 70, Difficulty: 2},
	{ID: "q9-7", Grade: 9, Topic: "Четыре ящика", Text: "4 ящика, в одном Кристалл. Надписи:\n1: «Кристалл в ящике 2».\n2: «Кристалл не в ящике 3».\n3: «Кристалл в ящике 4».\n4: «Кристалл не в ящике 2».\nРовно две надписи истинны. Где Кристалл?", Options: []string{"1", "2", "3", "4"}, CorrectAnswer: 3, Explanation: "Если в 4, истинны 2 и 3.", TimeLimitSeconds: 90, Difficulty: 2},
	{ID: "q9-8", Grade: 9, Topic: "Маршрут ровера", Text: "Ровер проехал: 3 м на север, 2 м на восток, 1 м на юг, 4 м на запад. На сколько метров он сместился по горизонтали и вертикали от старта?", Options: []string{"2 зап, 2 сев", "1 зап, 3 сев", "2 вос, 2 сев", "0, 0"}, CorrectAnswer: 0, Explanation: "Горизонталь: 2-4 = -2 (запад), вертикаль: 3-1 = 2 (север).", TimeLimitSeconds: 75, Difficulty: 2},
	{ID: "q9-9", Grade: 9, Topic: "Пять капсул", Text: "Капсулы в ряд. Красная левее синей, зелёная правее синей, жёлтая левее красной. Какая капсула точно не может быть самой левой?", Options: []string{"Жёлтая", "Красная", "Синяя", "Зелёная"}, CorrectAnswer: 3, Explanation: "Зелёная правее синей, значит не крайняя левая.", TimeLimitSeconds: 60, Difficulty: 1},
	{ID: "q9-10", Grade: 9, Topic: "Взвешивание шаров", Text: "9 энергошаров, один тяжелее. Чашечные весы. За сколько взвешиваний гарантированно найти тяжёлый?", Options: []string{"1", "2", "3", "4"}, CorrectAnswer: 1, Explanation: "Делим на 3 группы по 3.", TimeLimitSeconds: 60, Difficulty: 2},
	{ID: "q9-11", Grade: 9, Topic: "Правдивые пилоты", Text: "Аня: «Кристалл у Бори». Боря: «Кристалл у Вики». Вика: «У меня нет Кристалла». Ровно один сказал правду. У кого Кристалл?", Options: []string{"Аня", "Боря", "Вика"}, CorrectAnswer: 0, Explanation: "Если у Ани, правду говорит только Вика.", TimeLimitSeconds: 80, Difficulty: 2},
	{ID: "q9-12", Grade: 9, Topic: "Сигнал маяка", Text: "Маяк мигает: 1, 2, 4, 7, 11, ?\nКакое число следующее?", Options: []string{"14", "15", "16", "18"}, CorrectAnswer: 2, Explanation: "Разности +1,+2,+3,+4,+5.", TimeLimitSeconds: 50, Difficulty: 1},
	{ID: "q9-13", Grade: 9, Topic: "Запертая комната", Text: "3 кнопки, 3 лампы за стеной. Можно включать кнопки сколько угодно, но зайти к лампам можно один раз. Как определить соответствие?", Options: []string{"Включить все и зайти", "Включить первую на 5 мин, выключить, включить вторую, зайти", "Смотреть под дверь", "Спросить у робота"}, CorrectAnswer: 1, Explanation: "Горящая – вторая, тёплая выключенная – первая, холодная – третья.", TimeLimitSeconds: 90, Difficulty: 2},
	{ID: "q9-14", Grade: 9, Topic: "Два пути", Text: "Один путь безопасен, другой опасен. Два стража: один всегда лжёт, другой всегда говорит правду. Какой один вопрос задать любому, чтобы выбрать безопасный путь?", Options: []string{"Где безопасный путь?", "Какой путь другой назвал бы безопасным?", "Ты правдивый?", "Ты лжец?"}, CorrectAnswer: 1, Explanation: "Оба укажут на опасный путь.", TimeLimitSeconds: 75, Difficulty: 2},
	{ID: "q9-15", Grade: 9, Topic: "Кристалл и коробки", Text: "Золотая: «Кристалл не в серебряной». Серебряная: «Кристалл в чёрной». Чёрная: «Кристалл не здесь». Только одна надпись истинна. Где Кристалл?", Options: []string{"Золотая", "Серебряная", "Чёрная"}, CorrectAnswer: 1, Explanation: "Если в серебряной, истинна только чёрная.", TimeLimitSeconds: 90, Difficulty: 2},
	{ID: "q9-16", Grade: 9, Topic: "Команды на старте", Text: "8 команд стоят по кругу. Команда делает ход через один сектор по часовой. Старт в секторе 1. Где будет после 5 ходов?", Options: []string{"3", "4", "5", "6"}, CorrectAnswer: 0, Explanation: "+10 секторов, 1+10=11 -> 3.", TimeLimitSeconds: 65, Difficulty: 2},
	{ID: "q9-17", Grade: 9, Topic: "Планетарный сейф", Text: "Код – двузначное число. При перестановке цифр число увеличивается на 27. Сумма цифр 9. Найдите исходное число.", Options: []string{"36", "45", "54", "27"}, CorrectAnswer: 0, Explanation: "63-36=27, 3+6=9.", TimeLimitSeconds: 70, Difficulty: 2},
	{ID: "q9-18", Grade: 9, Topic: "Очередь экипажей", Text: "Перед Мишей ровно два человека. За Мишей ровно три человека. Сколько всего человек?", Options: []string{"5", "6", "7", "8"}, CorrectAnswer: 1, Explanation: "2+1+3=6.", TimeLimitSeconds: 50, Difficulty: 1},
	{ID: "q9-19", Grade: 9, Topic: "Невидимый сектор", Text: "12 секторов, 5 безопасны. Могут ли все безопасные стоять так, что между любыми двумя соседними безопасными секторами есть хотя бы один опасный?", Options: []string{"Да", "Нет", "Зависит от расположения"}, CorrectAnswer: 1, Explanation: "Максимум 6 безопасных при чередовании, 5 можно разместить с промежутками.", TimeLimitSeconds: 60, Difficulty: 1},
	{ID: "q9-20", Grade: 9, Topic: "Последний заряд", Text: "10 батарей. Каждый час: если чётное – половина расходуется, если нечётное – добавляется одна резервная, затем половина. Сколько останется через 2 часа?", Options: []string{"2", "3", "4", "5"}, CorrectAnswer: 1, Explanation: "10->5, 5+1=6->3.", TimeLimitSeconds: 80, Difficulty: 2},

	// перенесены из бывшего 10 класса (простые / средние)
	{ID: "q10-5", Grade: 9, Topic: "Рекурсивный расчёт", Text: "Функция f(n): если n=0 то 0, иначе n+f(n-1). Чему равно f(6)?", Options: []string{"15", "18", "21", "24"}, CorrectAnswer: 2, Explanation: "Сумма 1..6 = 21.", TimeLimitSeconds: 45, Difficulty: 1},
	{ID: "q10-8", Grade: 9, Topic: "Булева алгебра", Text: "Упростите (A И НЕ B) ИЛИ (A И B).", Options: []string{"A", "B", "A И B", "A ИЛИ B"}, CorrectAnswer: 0, Explanation: "A & (!B | B) = A.", TimeLimitSeconds: 55, Difficulty: 1},
	{ID: "q10-9", Grade: 9, Topic: "Кодирование сообщений", Text: "Сообщение из 200 символов алфавита мощностью 64. Минимальный размер в битах?", Options: []string{"800", "1000", "1200", "1600"}, CorrectAnswer: 2, Explanation: "6 бит на символ, 200*6=1200.", TimeLimitSeconds: 55, Difficulty: 2},
	{ID: "q10-11", Grade: 9, Topic: "Система допуска", Text: "Доступ разрешён, если (роль admin ИЛИ moderator) И НЕ заблокирован. Пользователь admin, но заблокирован. Пройдёт?", Options: []string{"Да", "Нет", "Только moderator", "Зависит от пароля"}, CorrectAnswer: 1, Explanation: "(true OR false) AND NOT true = false.", TimeLimitSeconds: 55, Difficulty: 1},
	{ID: "q10-12", Grade: 9, Topic: "Стековая память", Text: "В стек положили 1, 2, 3, затем дважды извлекли. Что на вершине?", Options: []string{"1", "2", "3", "Стек пуст"}, CorrectAnswer: 0, Explanation: "После push: [1,2,3] (вершина 3). pop->3, pop->2, остался [1].", TimeLimitSeconds: 50, Difficulty: 1},
	{ID: "q10-13", Grade: 9, Topic: "Гонка на выживание", Text: "В гонке 5 пилотов. A быстрее B, B быстрее C, D медленнее E, но быстрее A. Кто самый быстрый?", Options: []string{"A", "B", "C", "E"}, CorrectAnswer: 3, Explanation: "E > D > A > B > C.", TimeLimitSeconds: 70, Difficulty: 2},
	{ID: "q10-15", Grade: 9, Topic: "Чередование сигналов", Text: "Сигналы: 0, 3, 8, 15, 24, ?", Options: []string{"30", "33", "35", "36"}, CorrectAnswer: 2, Explanation: "n²-1: 1²-1=0, 2²-1=3, 3²-1=8, ... 6²-1=35.", TimeLimitSeconds: 60, Difficulty: 2},
	{ID: "q10-18", Grade: 9, Topic: "Перестановки экипажа", Text: "Сколькими способами можно рассадить 4 членов экипажа в ряд?", Options: []string{"12", "16", "24", "48"}, CorrectAnswer: 2, Explanation: "4! = 24.", TimeLimitSeconds: 40, Difficulty: 1},
	{ID: "q10-19", Grade: 9, Topic: "Секретная частота", Text: "Два маяка мигают с периодами 6 и 8 секунд. Через сколько секунд они мигнут одновременно в следующий раз?", Options: []string{"12", "24", "48", "36"}, CorrectAnswer: 1, Explanation: "НОК(6,8)=24.", TimeLimitSeconds: 50, Difficulty: 1},
	{ID: "q10-20", Grade: 9, Topic: "Минимальное число", Text: "В ящике 4 красных, 5 синих, 6 зелёных кристаллов. Сколько нужно вытащить вслепую, чтобы гарантированно получить хотя бы 3 одного цвета?", Options: []string{"5", "6", "7", "8"}, CorrectAnswer: 2, Explanation: "Худший случай: по 2 каждого = 6, следующий даст 3.", TimeLimitSeconds: 60, Difficulty: 2},

	// ================== 11 КЛАСС ==================
	{ID: "q11-1", Grade: 11, Topic: "Три экипажа", Text: "Экипажи A, B, C на планетах Лира, Нова, Эхо. A: «Я не на Лире». B: «C на Эхо». C: «B не на Нове». Ровно два утверждения истинны. B на Лире. Где C?", Options: []string{"Лира", "Нова", "Эхо"}, CorrectAnswer: 2, Explanation: "B на Лире → C на Эхо (по утверждению B), проверка даёт ровно две истины.", TimeLimitSeconds: 90, Difficulty: 3},
	{ID: "q11-2", Grade: 11, Topic: "Лжецы на станции", Text: "4 робота. Каждый либо правдив, либо лжец.\n1: «Среди нас 1 лжец».\n2: «Среди нас 2 лжеца».\n3: «Среди нас 3 лжеца».\n4: «Среди нас 4 лжеца».\nСколько лжецов?", Options: []string{"1", "2", "3", "4"}, CorrectAnswer: 2, Explanation: "Если правдив только 3-й, то лжецов 3.", TimeLimitSeconds: 90, Difficulty: 3},
	{ID: "q11-3", Grade: 11, Topic: "Сейф с Кристаллом", Text: "5 сейфов, в одном Кристалл. Надписи:\n1: «В 2 или 3».\n2: «Не в 1».\n3: «В 5».\n4: «Не в 5».\n5: «В 4».\nРовно две истинны. Где Кристалл?", Options: []string{"1", "2", "3", "4", "5"}, CorrectAnswer: 4, Explanation: "Если в 5, истинны 2 и 3.", TimeLimitSeconds: 100, Difficulty: 3},
	{ID: "q11-4", Grade: 11, Topic: "Паритетный мост", Text: "На числовой прямой старт в 0. За ход можно +3 или -5. Можно ли попасть в точку 1?", Options: []string{"Да", "Нет"}, CorrectAnswer: 0, Explanation: "+3+3-5=1.", TimeLimitSeconds: 75, Difficulty: 2},
	{ID: "q11-5", Grade: 11, Topic: "Сумма положительных", Text: "6 целых чисел. Сумма любых пяти положительна. Обязательно ли сумма всех шести положительна?", Options: []string{"Да", "Нет", "Зависит от чисел"}, CorrectAnswer: 0, Explanation: "Сложив все 6 сумм, получим 5*общая сумма > 0.", TimeLimitSeconds: 80, Difficulty: 2},
	{ID: "q11-6", Grade: 11, Topic: "Парадокс двери", Text: "На двери две фразы:\n1) «Обе фразы ложны».\n2) «Кристалл за дверью».\nМожет ли первая быть истинной?", Options: []string{"Да", "Нет", "Если Кристалл есть"}, CorrectAnswer: 1, Explanation: "Если первая истинна, она должна быть ложна – противоречие.", TimeLimitSeconds: 70, Difficulty: 2},
	{ID: "q11-7", Grade: 11, Topic: "Финиш гонки", Text: "A, B, C финишировали. A: «Я не первый». B: «Я не последний». C: «Я первый». Ровно одно утверждение ложно. Кто первый?", Options: []string{"A", "B", "C"}, CorrectAnswer: 1, Explanation: "Если B первый, A правда, B правда, C ложь – одна ложь.", TimeLimitSeconds: 90, Difficulty: 3},
	{ID: "q11-8", Grade: 11, Topic: "Инвариант топлива", Text: "В баках 7 и 10 единиц. Можно переливать 2 единицы из одного в другой. Можно ли получить 8 и 9?", Options: []string{"Да", "Нет"}, CorrectAnswer: 1, Explanation: "Чётность 7 и 10 сохраняется, 8 и 9 имеют обратную.", TimeLimitSeconds: 70, Difficulty: 2},
	{ID: "q11-9", Grade: 11, Topic: "Секретный порядок", Text: "A левее B. C правее D. B левее D. E правее C. Кто может быть первым?", Options: []string{"A", "B", "C", "D", "E"}, CorrectAnswer: 0, Explanation: "Только A может быть крайним левым.", TimeLimitSeconds: 90, Difficulty: 2},
	{ID: "q11-10", Grade: 11, Topic: "Дележ артефактов", Text: "15 артефактов. За ход можно взять 1, 2 или 3. Побеждает взявший последний. Какой первый ход гарантирует победу первому игроку?", Options: []string{"1", "2", "3", "Нельзя гарантировать"}, CorrectAnswer: 2, Explanation: "Оставить 12 (кратно 4).", TimeLimitSeconds: 80, Difficulty: 2},
	{ID: "q11-11", Grade: 11, Topic: "Кодовая разница", Text: "Трёхзначный код с разными цифрами. Сумма цифр 15. Если цифры переставить в обратном порядке, число увеличится на 198. Найдите код.", Options: []string{"357", "456", "654", "753"}, CorrectAnswer: 1, Explanation: "654-456=198, сумма 15.", TimeLimitSeconds: 100, Difficulty: 3},
	{ID: "q11-12", Grade: 11, Topic: "Два выключателя", Text: "2 выключателя, 2 лампы. Зайти можно один раз. Можно ли определить соответствие?", Options: []string{"Да, включив оба", "Да, включив один на время", "Нет, нужно заходить дважды", "Только если лампы видны"}, CorrectAnswer: 1, Explanation: "Аналогично задаче с тремя лампами.", TimeLimitSeconds: 70, Difficulty: 2},
	{ID: "q11-13", Grade: 11, Topic: "Календарь планеты", Text: "Неделя 5 дней. Сегодня день 2. Какой день будет через 17 дней?", Options: []string{"1", "2", "3", "4"}, CorrectAnswer: 3, Explanation: "17 mod 5 = 2, 2+2=4.", TimeLimitSeconds: 50, Difficulty: 1},
	{ID: "q11-14", Grade: 11, Topic: "Группа разведчиков", Text: "В группе 10 разведчиков, каждый знаком ровно с 3 другими. Возможно ли это?", Options: []string{"Да", "Нет", "Только если есть изолированные"}, CorrectAnswer: 0, Explanation: "Сумма степеней 30, чётна, такой граф существует.", TimeLimitSeconds: 60, Difficulty: 2},
	{ID: "q11-15", Grade: 11, Topic: "Минимум гарантий", Text: "В ящике 5 красных, 7 синих, 9 зелёных кристаллов. Сколько нужно достать вслепую, чтобы гарантированно получить 3 одного цвета?", Options: []string{"5", "6", "7", "8"}, CorrectAnswer: 2, Explanation: "Худший случай: по 2 каждого = 6, следующий даст 3.", TimeLimitSeconds: 60, Difficulty: 2},
	{ID: "q11-16", Grade: 11, Topic: "Логика допуска", Text: "Допуск к посадке: хотя бы два из трёх условий: есть топливо, карта, пилот. Топлива нет, карта есть, пилот есть. Допуск разрешён?", Options: []string{"Да", "Нет"}, CorrectAnswer: 0, Explanation: "Два условия выполнены.", TimeLimitSeconds: 50, Difficulty: 1},
	{ID: "q11-17", Grade: 11, Topic: "Последовательность сигналов", Text: "2, 6, 12, 20, 30, ?", Options: []string{"38", "40", "42", "44"}, CorrectAnswer: 2, Explanation: "n(n+1): 6*7=42.", TimeLimitSeconds: 60, Difficulty: 2},
	{ID: "q11-18", Grade: 11, Topic: "Обмен местами", Text: "Ряд A,B,C,D. Менять можно только соседей. Сколько минимально обменов до D,C,B,A?", Options: []string{"4", "5", "6", "7"}, CorrectAnswer: 2, Explanation: "Инверсии: D перед A,B,C (3), C перед A,B (2), B перед A (1) = 6.", TimeLimitSeconds: 80, Difficulty: 2},
	{ID: "q11-19", Grade: 11, Topic: "Круглая станция", Text: "8 шлюзов по кругу. Команда переходит через 3 шлюза по часовой. Сколько разных шлюзов посетит, прежде чем вернётся в начальный?", Options: []string{"2", "4", "6", "8"}, CorrectAnswer: 3, Explanation: "3 и 8 взаимно просты, обойдёт все.", TimeLimitSeconds: 70, Difficulty: 2},
	{ID: "q11-20", Grade: 11, Topic: "Последнее утверждение", Text: "Табличка: «Следующее предложение истинно. Предыдущее предложение ложно». Можно ли сделать обе фразы истинными?", Options: []string{"Да", "Нет", "Если Кристалл рядом"}, CorrectAnswer: 1, Explanation: "Противоречат друг другу.", TimeLimitSeconds: 60, Difficulty: 2},

	{ID: "q10-1", Grade: 11, Topic: "Импульсный протокол", Text: "Если зонд отправляет сигнал, то станция его принимает. Станция не приняла сигнал. Что можно сказать о зонде?", Options: []string{"Зонд не отправлял сигнал", "Зонд отправил сигнал", "Зонд сломан", "Станция неисправна"}, CorrectAnswer: 0, Explanation: "Модус толленс: A→B, не B → не A.", TimeLimitSeconds: 60, Difficulty: 2},
	{ID: "q10-2", Grade: 11, Topic: "Кристаллическая решётка", Text: "Сколько сравнений в худшем случае потребуется бинарному поиску в отсортированном массиве из 2048 элементов?", Options: []string{"11", "12", "1024", "2048"}, CorrectAnswer: 1, Explanation: "log2(2048)=11, но худший случай 12 сравнений.", TimeLimitSeconds: 60, Difficulty: 2},
	{ID: "q10-4", Grade: 11, Topic: "Сеть дальней связи", Text: "IP-адрес 10.0.0.130/26. Какой адрес сети?", Options: []string{"10.0.0.0", "10.0.0.64", "10.0.0.128", "10.0.0.192"}, CorrectAnswer: 2, Explanation: "/26 блоки по 64 адреса. 130 в диапазоне 128-191.", TimeLimitSeconds: 90, Difficulty: 3},
	{ID: "q10-6", Grade: 11, Topic: "Хеш-безопасность", Text: "Как лучше всего защитить пароли при утечке базы?", Options: []string{"Хранить открытым текстом", "Шифровать общим ключом", "Солёный хеш (bcrypt/argon2)", "Кодировать в Base64"}, CorrectAnswer: 2, Explanation: "Солёный хеш устойчив к радужным таблицам.", TimeLimitSeconds: 60, Difficulty: 2},
	{ID: "q10-7", Grade: 11, Topic: "Асимптотика", Text: "Внешний цикл n раз, внутренний n/2 раз. Асимптотика общего числа операций?", Options: []string{"O(n)", "O(log n)", "O(n²)", "O(2ⁿ)"}, CorrectAnswer: 2, Explanation: "n*(n/2) ~ n²/2 → O(n²).", TimeLimitSeconds: 50, Difficulty: 2},
	{ID: "q10-10", Grade: 11, Topic: "Постфиксная запись", Text: "Вычислите: 5 2 3 * + 4 −", Options: []string{"3", "7", "9", "15"}, CorrectAnswer: 1, Explanation: "2*3=6, 5+6=11, 11-4=7.", TimeLimitSeconds: 75, Difficulty: 2},
	{ID: "q10-14", Grade: 11, Topic: "Пароль отсека", Text: "Пароль – трёхзначное число, все цифры различны. Сумма цифр 10. Если поменять местами первую и последнюю цифры, число уменьшится на 198. Найдите пароль.", Options: []string{"316", "406", "514", "604"}, CorrectAnswer: 3, Explanation: "604-406=198, сумма 6+0+4=10.", TimeLimitSeconds: 100, Difficulty: 3},
	{ID: "q10-16", Grade: 11, Topic: "Логический парадокс", Text: "Робот говорит: «Это утверждение ложно». Является ли оно истинным?", Options: []string{"Да", "Нет", "Парадокс, не разрешимо"}, CorrectAnswer: 2, Explanation: "Классический парадокс лжеца.", TimeLimitSeconds: 70, Difficulty: 2},
	{ID: "q10-17", Grade: 11, Topic: "Энергетический баланс", Text: "В двух аккумуляторах 5 и 8 единиц энергии. Можно переливать по 2 единицы из одного в другой. Можно ли получить 6 и 7?", Options: []string{"Да", "Нет"}, CorrectAnswer: 1, Explanation: "Чётность 5 и 8 сохраняется, 6 и 7 имеют другую чётность.", TimeLimitSeconds: 80, Difficulty: 2},
}

var tasks = []models.TerminalTask{
	// ================== 9 КЛАСС ==================
	{ID: "py9-1", Title: "Сумма энергии", Description: "Дан список уровней энергии модулей. Выведите сумму положительных чисел.\nПример: 5 -2 7 0 -1 → 12", Language: "python", StarterCode: "nums = list(map(int, input().split()))\nresult = ...", AcceptedAnswers: []string{"sum(x for x in nums if x > 0)"}, Reward: 260, Difficulty: 2, Grade: 9},
	{ID: "py9-2", Title: "Кристалл делимости", Description: "Дано число n. Выведите YES, если сумма его цифр делится на 3, иначе NO.", Language: "python", StarterCode: "n = int(input())\nresult = ...", AcceptedAnswers: []string{"'YES' if sum(int(d) for d in str(n)) % 3 == 0 else 'NO'"}, Reward: 220, Difficulty: 1, Grade: 9},
	{ID: "py9-3", Title: "Первый максимум", Description: "Дан список сигналов. Выведите максимальный сигнал и индекс его первого появления.", Language: "python", StarterCode: "signals = list(map(int, input().split()))\nmx = max(signals)\nprint(mx, signals.index(mx))", AcceptedAnswers: []string{"print(max(signals), signals.index(max(signals)))"}, Reward: 280, Difficulty: 2, Grade: 9},
	{ID: "py9-4", Title: "Пароль шлюза", Description: "Дана строка. Выведите YES, если длина не меньше 8 и есть хотя бы одна цифра.", Language: "python", StarterCode: "s = input()\nresult = ...", AcceptedAnswers: []string{"'YES' if len(s) >= 8 and any(c.isdigit() for c in s) else 'NO'"}, Reward: 240, Difficulty: 1, Grade: 9},
	{ID: "py9-5", Title: "Робот-разведчик", Description: "Дана строка команд N, S, E, W. Старт (0,0). Выведите конечные координаты.", Language: "python", StarterCode: "commands = input().split()\nx = y = 0\n# ваш код", AcceptedAnswers: []string{"for cmd in commands:\n    if cmd == 'N': y += 1\n    elif cmd == 'S': y -= 1\n    elif cmd == 'E': x += 1\n    elif cmd == 'W': x -= 1\nprint(x, y)"}, Reward: 300, Difficulty: 2, Grade: 9},
	{ID: "py9-6", Title: "Одинокие сигналы", Description: "Даны числа. Выведите только те, которые встречаются ровно один раз.", Language: "python", StarterCode: "nums = list(map(int, input().split()))\n# ваш код", AcceptedAnswers: []string{"freq = {}\nfor x in nums: freq[x] = freq.get(x, 0) + 1\nprint(*[x for x in nums if freq[x] == 1])"}, Reward: 320, Difficulty: 2, Grade: 9},
	{ID: "py9-7", Title: "Сжатие RLE", Description: "Дана строка заглавных букв. Сожмите её: AAABB → A3B2.", Language: "python", StarterCode: "s = input()\n# ваш код", AcceptedAnswers: []string{"res = ''\ni = 0\nwhile i < len(s):\n    j = i\n    while j < len(s) and s[j] == s[i]:\n        j += 1\n    res += s[i] + str(j - i)\n    i = j\nprint(res)"}, Reward: 340, Difficulty: 3, Grade: 9},
	{ID: "py9-8", Title: "Расшифровка Цезаря", Description: "Дана строка из строчных букв, зашифрованная сдвигом вперёд на 1. Верните исходную.", Language: "python", StarterCode: "s = input()\n# ваш код", AcceptedAnswers: []string{"''.join(chr((ord(c) - 97 - 1) % 26 + 97) for c in s)"}, Reward: 260, Difficulty: 2, Grade: 9},
	{ID: "py9-9", Title: "Космический палиндром", Description: "Дана строка. Игнорируя пробелы и регистр, проверьте, палиндром ли она.", Language: "python", StarterCode: "s = input()\n# ваш код", AcceptedAnswers: []string{"s2 = ''.join(c.lower() for c in s if c.isalpha())\nprint('YES' if s2 == s2[::-1] else 'NO')"}, Reward: 300, Difficulty: 2, Grade: 9},
	{ID: "py9-10", Title: "Минимальный расход", Description: "Дан список расходов топлива. Найдите минимальный расход и сколько раз он встретился.", Language: "python", StarterCode: "a = list(map(int, input().split()))\n# ваш код", AcceptedAnswers: []string{"mn = min(a)\nprint(mn, a.count(mn))"}, Reward: 220, Difficulty: 1, Grade: 9},
	{ID: "py9-11", Title: "Ближайшие сигналы", Description: "Дан список чисел. Найдите минимальную разницу между двумя различными элементами.", Language: "python", StarterCode: "nums = list(map(int, input().split()))\n# ваш код", AcceptedAnswers: []string{"nums.sort()\nprint(min(nums[i+1]-nums[i] for i in range(len(nums)-1)))"}, Reward: 360, Difficulty: 3, Grade: 9},
	{ID: "py9-12", Title: "Осевые точки", Description: "Даны координаты точек. Выведите количество точек, лежащих на осях (x==0 или y==0).", Language: "python", StarterCode: "n = int(input())\ncnt = 0\n# ваш код", AcceptedAnswers: []string{"for _ in range(n):\n    x, y = map(int, input().split())\n    if x == 0 or y == 0: cnt += 1\nprint(cnt)"}, Reward: 280, Difficulty: 2, Grade: 9},
	{ID: "py9-13", Title: "Средний рейтинг", Description: "Даны баллы участников. Выведите средний балл, округлённый вниз.", Language: "python", StarterCode: "scores = list(map(int, input().split()))\nprint(sum(scores) // len(scores))", AcceptedAnswers: []string{"print(sum(scores) // len(scores))"}, Reward: 200, Difficulty: 1, Grade: 9},
	{ID: "py9-14", Title: "Поиск команды", Description: "Дана строка с названиями команд через запятую и отдельное название. Проверьте, есть ли команда.", Language: "python", StarterCode: "teams = input().split(',')\ntarget = input()\n# ваш код", AcceptedAnswers: []string{"print('YES' if target in teams else 'NO')"}, Reward: 200, Difficulty: 1, Grade: 9},
	{ID: "py9-15", Title: "Лишний символ", Description: "Вторая строка получена из первой добавлением одного символа. Найдите этот символ.", Language: "python", StarterCode: "s1 = input()\ns2 = input()\n# ваш код", AcceptedAnswers: []string{"from collections import Counter\nc1, c2 = Counter(s1), Counter(s2)\nfor k in c2:\n    if c2[k] != c1.get(k, 0):\n        print(k); break"}, Reward: 380, Difficulty: 3, Grade: 9},
	{ID: "py9-16", Title: "Двоичный маяк", Description: "Дано десятичное число. Выведите его двоичное представление (без '0b').", Language: "python", StarterCode: "n = int(input())\n# ваш код", AcceptedAnswers: []string{"print(bin(n)[2:])"}, Reward: 180, Difficulty: 1, Grade: 9},
	{ID: "py9-17", Title: "Частая буква", Description: "Дана строка. Выведите самую частую букву (при равенстве – меньшую по алфавиту).", Language: "python", StarterCode: "s = input()\n# ваш код", AcceptedAnswers: []string{"freq = {}\nfor c in s:\n    if c.isalpha():\n        freq[c] = freq.get(c, 0) + 1\nmx = max(freq.values())\nprint(min(k for k, v in freq.items() if v == mx))"}, Reward: 340, Difficulty: 2, Grade: 9},
	{ID: "py9-18", Title: "Уникальность ID", Description: "Дан список ID участников. Выведите YES, если все ID уникальны.", Language: "python", StarterCode: "ids = input().split()\n# ваш код", AcceptedAnswers: []string{"print('YES' if len(ids) == len(set(ids)) else 'NO')"}, Reward: 220, Difficulty: 1, Grade: 9},
	{ID: "py9-19", Title: "Сдвиг очереди", Description: "Дан список команд и число k. Сдвиньте список влево на k позиций.", Language: "python", StarterCode: "arr = input().split()\nk = int(input())\n# ваш код", AcceptedAnswers: []string{"k %= len(arr)\nprint(*(arr[k:] + arr[:k]))"}, Reward: 300, Difficulty: 2, Grade: 9},
	{ID: "py9-20", Title: "Безопасный маршрут", Description: "Даны высоты рельефа. Маршрут безопасен, если соседние отличаются не более чем на 3. Выведите YES/NO.", Language: "python", StarterCode: "h = list(map(int, input().split()))\n# ваш код", AcceptedAnswers: []string{"print('YES' if all(abs(h[i+1]-h[i]) <= 3 for i in range(len(h)-1)) else 'NO')"}, Reward: 320, Difficulty: 2, Grade: 9},


	{ID: "py10-2", Title: "Скобочный протокол", Description: "Дана строка из (), [], {}. Определите, корректна ли она.", Language: "python", StarterCode: "s = input()\n# ваш код", AcceptedAnswers: []string{"stack = []\npairs = {')': '(', ']': '[', '}': '{'}\nfor c in s:\n    if c in '([{': stack.append(c)\n    elif stack and stack[-1] == pairs.get(c): stack.pop()\n    else: print('NO'); break\nelse: print('YES' if not stack else 'NO')"}, Reward: 380, Difficulty: 2, Grade: 9},
	{ID: "py10-10", Title: "Частые сигналы", Description: "Дан массив и число k. Выведите k самых частых элементов.", Language: "python", StarterCode: "from collections import Counter\nimport heapq\narr = list(map(int, input().split()))\nk = int(input())\n# ваш код", AcceptedAnswers: []string{"cnt = Counter(arr)\nprint(*[x[0] for x in heapq.nlargest(k, cnt.items(), key=lambda x: x[1])])"}, Reward: 450, Difficulty: 2, Grade: 9},
	{ID: "sql10-1", Title: "Рейтинг экипажей", Description: "Таблица crew(team_id, score). Выведите team_id и сумму очков, отсортировав по убыванию суммы.", Language: "sql", StarterCode: "SELECT ...", AcceptedAnswers: []string{"SELECT team_id, SUM(score) AS total FROM crew GROUP BY team_id ORDER BY total DESC"}, Reward: 350, Difficulty: 2, Grade: 9},
	{ID: "sql10-2", Title: "Активность игроков", Description: "Таблица answers(player_id, is_correct). Выведите player_id и количество верных ответов.", Language: "sql", StarterCode: "SELECT ...", AcceptedAnswers: []string{"SELECT player_id, COUNT(*) FROM answers WHERE is_correct = true GROUP BY player_id"}, Reward: 320, Difficulty: 2, Grade: 9},
	{ID: "py10-16", Title: "Палиндромная перестановка", Description: "Дана строка. Можно ли переставить буквы так, чтобы получился палиндром?", Language: "python", StarterCode: "s = input()\n# ваш код", AcceptedAnswers: []string{"from collections import Counter\ncnt = Counter(s)\nodd = sum(v % 2 for v in cnt.values())\nprint('YES' if odd <= 1 else 'NO')"}, Reward: 280, Difficulty: 2, Grade: 9},
	{ID: "py10-18", Title: "Бинарный поиск", Description: "Дан отсортированный массив и число x. Найдите индекс x или -1.", Language: "python", StarterCode: "arr = list(map(int, input().split()))\nx = int(input())\n# ваш код", AcceptedAnswers: []string{"lo, hi = 0, len(arr)-1\nwhile lo <= hi:\n    mid = (lo+hi)//2\n    if arr[mid] == x:\n        print(mid)\n        break\n    elif arr[mid] < x: lo = mid+1\n    else: hi = mid-1\nelse: print(-1)"}, Reward: 260, Difficulty: 2, Grade: 9},

	// ================== 11 КЛАСС ==================
	{ID: "py11-1", Title: "Дейкстра: курс на Кристалл", Description: "Дан граф (матрица смежности) и стартовая вершина. Выведите кратчайшие расстояния до всех вершин.", Language: "python", StarterCode: "import heapq\ndef dijkstra(graph, start):\n    n = len(graph)\n    dist = [float('inf')] * n\n    dist[start] = 0\n    pq = [(0, start)]\n    while pq:\n        d, u = heapq.heappop(pq)\n        if d > dist[u]: continue\n        for v, w in enumerate(graph[u]):\n            if w and dist[v] > d + w:\n                dist[v] = d + w\n                heapq.heappush(pq, (dist[v], v))\n    return dist", AcceptedAnswers: []string{}, Reward: 500, Difficulty: 3, Grade: 11},
	{ID: "py11-2", Title: "Скобочная последовательность", Description: "Дана строка из (), [], {}. Проверьте её корректность.", Language: "python", StarterCode: "s = input()\n# ваш код", AcceptedAnswers: []string{"stack = []\npairs = {')': '(', ']': '[', '}': '{'}\nfor c in s:\n    if c in '([{': stack.append(c)\n    elif stack and stack[-1] == pairs.get(c): stack.pop()\n    else: print('NO'); break\nelse: print('YES' if not stack else 'NO')"}, Reward: 380, Difficulty: 2, Grade: 11},
	{ID: "py11-3", Title: "Острова в туманности", Description: "Дана матрица 0 и 1. Посчитайте количество островов.", Language: "python", StarterCode: "grid = []\nwhile True:\n    try:\n        row = input()\n        if row == '': break\n        grid.append(list(map(int, row.split())))\n    except: break\n# ваш код", AcceptedAnswers: []string{"def dfs(i, j):\n    if 0 <= i < len(grid) and 0 <= j < len(grid[0]) and grid[i][j]:\n        grid[i][j] = 0\n        for di, dj in ((0,1),(0,-1),(1,0),(-1,0)):\n            dfs(i+di, j+dj)\ncount = 0\nfor i in range(len(grid)):\n    for j in range(len(grid[0])):\n        if grid[i][j]:\n            dfs(i, j)\n            count += 1\nprint(count)"}, Reward: 550, Difficulty: 3, Grade: 11},
	{ID: "py11-4", Title: "Анаграммные группы", Description: "Дан список слов. Сгруппируйте анаграммы и выведите каждую группу на новой строке.", Language: "python", StarterCode: "words = input().split()\n# ваш код", AcceptedAnswers: []string{"from collections import defaultdict\ngroups = defaultdict(list)\nfor w in words:\n    groups[''.join(sorted(w))].append(w)\nfor g in groups.values():\n    print(*g)"}, Reward: 420, Difficulty: 2, Grade: 11},
	{ID: "py11-5", Title: "Максимальный подотрезок", Description: "Дан массив чисел. Найдите максимальную сумму непрерывного подотрезка.", Language: "python", StarterCode: "nums = list(map(int, input().split()))\n# ваш код", AcceptedAnswers: []string{"mx = cur = nums[0]\nfor x in nums[1:]:\n    cur = max(x, cur + x)\n    mx = max(mx, cur)\nprint(mx)"}, Reward: 400, Difficulty: 2, Grade: 11},
	{ID: "py11-6", Title: "Распределение задач", Description: "Даны времена задач. Распределите их между двумя модулями с минимальной разницей сумм.", Language: "python", StarterCode: "times = list(map(int, input().split()))\n# ваш код", AcceptedAnswers: []string{"total = sum(times)\ndp = {0}\nfor t in times:\n    dp |= {x + t for x in dp}\nprint(min(abs(total - 2*s) for s in dp))"}, Reward: 600, Difficulty: 3, Grade: 11},
	{ID: "py11-7", Title: "Топологическая сортировка", Description: "Дан граф зависимостей. Выведите возможный порядок запуска систем.", Language: "python", StarterCode: "from collections import deque\ndef topo_sort(n, edges):\n    indeg = [0]*n\n    g = [[] for _ in range(n)]\n    for u, v in edges:\n        g[u].append(v)\n        indeg[v] += 1\n    q = deque([i for i in range(n) if indeg[i] == 0])\n    res = []\n    while q:\n        u = q.popleft()\n        res.append(u)\n        for v in g[u]:\n            indeg[v] -= 1\n            if indeg[v] == 0:\n                q.append(v)\n    return res if len(res) == n else []", AcceptedAnswers: []string{}, Reward: 550, Difficulty: 3, Grade: 11},
	{ID: "py11-8", Title: "Цикл в графе", Description: "Ориентированный граф. Определите наличие цикла.", Language: "python", StarterCode: "n = int(input())\nedges = []\nwhile True:\n    try:\n        u, v = map(int, input().split())\n        edges.append((u, v))\n    except: break\n# ваш код", AcceptedAnswers: []string{"from collections import defaultdict\ng = defaultdict(list)\nfor u, v in edges:\n    g[u].append(v)\nvisited = [0]*n\ndef dfs(u):\n    visited[u] = 1\n    for v in g[u]:\n        if visited[v] == 1: return True\n        if visited[v] == 0 and dfs(v): return True\n    visited[u] = 2\n    return False\nprint('YES' if any(dfs(i) for i in range(n) if visited[i] == 0) else 'NO')"}, Reward: 500, Difficulty: 3, Grade: 11},
	{ID: "py11-9", Title: "Связность сети", Description: "Неориентированный граф. Проверьте, можно ли добраться из любой вершины в любую.", Language: "python", StarterCode: "n = int(input())\nedges = []\nwhile True:\n    try:\n        u, v = map(int, input().split())\n        edges.append((u, v))\n    except: break\n# ваш код", AcceptedAnswers: []string{"g = [[] for _ in range(n)]\nfor u, v in edges:\n    g[u].append(v)\n    g[v].append(u)\nvisited = [False]*n\ndef dfs(u):\n    visited[u] = True\n    for v in g[u]:\n        if not visited[v]: dfs(v)\ndfs(0)\nprint('YES' if all(visited) else 'NO')"}, Reward: 400, Difficulty: 2, Grade: 11},
	{ID: "py11-10", Title: "Топ k частых", Description: "Дан массив и число k. Выведите k самых частых элементов.", Language: "python", StarterCode: "from collections import Counter\nimport heapq\narr = list(map(int, input().split()))\nk = int(input())\n# ваш код", AcceptedAnswers: []string{"cnt = Counter(arr)\nprint(*[x[0] for x in heapq.nlargest(k, cnt.items(), key=lambda x: x[1])])"}, Reward: 450, Difficulty: 2, Grade: 11},
	{ID: "py11-11", Title: "Минимальное окно подстроки", Description: "Дана строка s и набор t. Найдите минимальную подстроку s, содержащую все символы t.", Language: "python", StarterCode: "s, t = input().split()\n# ваш код", AcceptedAnswers: []string{"from collections import Counter\nneed = Counter(t)\nmissing = len(t)\nleft = start = end = 0\nres = ''\nfor right, c in enumerate(s):\n    if need[c] > 0: missing -= 1\n    need[c] -= 1\n    if missing == 0:\n        while need[s[left]] < 0:\n            need[s[left]] += 1\n            left += 1\n        if not res or right - left < end - start:\n            start, end = left, right\n            res = s[left:right+1]\n        need[s[left]] += 1\n        missing += 1\n        left += 1\nprint(res)"}, Reward: 650, Difficulty: 3, Grade: 11},
	{ID: "py11-12", Title: "Пути робота", Description: "Сетка с препятствиями, движение вправо/вниз. Количество путей из (0,0) в (n-1,m-1).", Language: "python", StarterCode: "n, m = map(int, input().split())\ngrid = [list(map(int, input().split())) for _ in range(n)]\n# ваш код", AcceptedAnswers: []string{"dp = [[0]*m for _ in range(n)]\nif grid[0][0]: dp[0][0] = 1\nfor i in range(n):\n    for j in range(m):\n        if grid[i][j] and not (i == 0 and j == 0):\n            dp[i][j] = (dp[i-1][j] if i else 0) + (dp[i][j-1] if j else 0)\nprint(dp[-1][-1])"}, Reward: 500, Difficulty: 2, Grade: 11},
	{ID: "py11-13", Title: "Рюкзак экспедиции", Description: "Даны веса и ценности, вместимость W. Найдите максимальную ценность (0-1 рюкзак).", Language: "python", StarterCode: "n, W = map(int, input().split())\nitems = [tuple(map(int, input().split())) for _ in range(n)]\n# ваш код", AcceptedAnswers: []string{"dp = [0]*(W+1)\nfor w, v in items:\n    for cap in range(W, w-1, -1):\n        dp[cap] = max(dp[cap], dp[cap-w] + v)\nprint(dp[W])"}, Reward: 600, Difficulty: 3, Grade: 11},
	{ID: "sql11-1", Title: "Командный рейтинг", Description: "Таблица results(team_id, score). Выведите team_id и сумму очков, отсортировав по убыванию.", Language: "sql", StarterCode: "SELECT ...", AcceptedAnswers: []string{"SELECT team_id, SUM(score) AS total FROM results GROUP BY team_id ORDER BY total DESC"}, Reward: 350, Difficulty: 2, Grade: 11},
	{ID: "sql11-2", Title: "Правильные ответы", Description: "Таблица answers(player_id, is_correct). Выведите player_id и количество правильных ответов.", Language: "sql", StarterCode: "SELECT ...", AcceptedAnswers: []string{"SELECT player_id, COUNT(*) FROM answers WHERE is_correct = true GROUP BY player_id"}, Reward: 320, Difficulty: 2, Grade: 11},
	{ID: "py11-16", Title: "Палиндромная перестановка", Description: "Дана строка. Можно ли переставить символы, чтобы получить палиндром?", Language: "python", StarterCode: "s = input()\n# ваш код", AcceptedAnswers: []string{"from collections import Counter\ncnt = Counter(s)\nodd = sum(v % 2 for v in cnt.values())\nprint('YES' if odd <= 1 else 'NO')"}, Reward: 280, Difficulty: 2, Grade: 11},
	{ID: "py11-17", Title: "Слияние интервалов", Description: "Дан список интервалов [start,end]. Объедините пересекающиеся.", Language: "python", StarterCode: "intervals = eval(input())\n# ваш код", AcceptedAnswers: []string{"intervals.sort()\nmerged = []\nfor s, e in intervals:\n    if not merged or merged[-1][1] < s:\n        merged.append([s, e])\n    else:\n        merged[-1][1] = max(merged[-1][1], e)\nprint(merged)"}, Reward: 420, Difficulty: 2, Grade: 11},
	{ID: "py11-18", Title: "Бинарный поиск", Description: "Дан отсортированный массив и x. Найдите индекс x или -1.", Language: "python", StarterCode: "arr = list(map(int, input().split()))\nx = int(input())\n# ваш код", AcceptedAnswers: []string{"lo, hi = 0, len(arr)-1\nwhile lo <= hi:\n    mid = (lo+hi)//2\n    if arr[mid] == x:\n        print(mid)\n        break\n    elif arr[mid] < x: lo = mid+1\n    else: hi = mid-1\nelse: print(-1)"}, Reward: 260, Difficulty: 2, Grade: 11},
	{ID: "py11-19", Title: "Прыжки к Кристаллу", Description: "Дан массив a[i] – максимальная длина прыжка из i. Минимальное число прыжков до конца.", Language: "python", StarterCode: "a = list(map(int, input().split()))\n# ваш код", AcceptedAnswers: []string{"jumps = 0\ncur_end = 0\nfarthest = 0\nfor i in range(len(a)-1):\n    farthest = max(farthest, i + a[i])\n    if i == cur_end:\n        jumps += 1\n        cur_end = farthest\nprint(jumps)"}, Reward: 500, Difficulty: 3, Grade: 11},
	{ID: "py11-20", Title: "Изоморфизм кодов", Description: "Строки s и t изоморфны? (отображение символов однозначно в обе стороны)", Language: "python", StarterCode: "s, t = input().split()\n# ваш код", AcceptedAnswers: []string{"m1, m2 = {}, {}\nfor a, b in zip(s, t):\n    if (a in m1 and m1[a] != b) or (b in m2 and m2[b] != a):\n        print('NO')\n        break\n    m1[a] = b\n    m2[b] = a\nelse: print('YES')"}, Reward: 450, Difficulty: 2, Grade: 11},

	{ID: "py10-1", Title: "Кратчайший путь", Description: "Дана матрица смежности графа и стартовая вершина. Найдите кратчайшие расстояния до всех вершин (алгоритм Дейкстры).", Language: "python", StarterCode: "import heapq\ndef dijkstra(graph, start):\n    n = len(graph)\n    dist = [float('inf')] * n\n    dist[start] = 0\n    pq = [(0, start)]\n    while pq:\n        d, u = heapq.heappop(pq)\n        if d > dist[u]: continue\n        for v, w in enumerate(graph[u]):\n            if w and dist[v] > d + w:\n                dist[v] = d + w\n                heapq.heappush(pq, (dist[v], v))\n    return dist", AcceptedAnswers: []string{}, Reward: 500, Difficulty: 3, Grade: 11},
	{ID: "py10-3", Title: "Острова на планете", Description: "Дана матрица из 0 и 1. Посчитайте количество островов.", Language: "python", StarterCode: "grid = []\nwhile True:\n    try:\n        row = input()\n        if row == '': break\n        grid.append(list(map(int, row.split())))\n    except: break\n# ваш код", AcceptedAnswers: []string{"def dfs(i, j):\n    if 0 <= i < len(grid) and 0 <= j < len(grid[0]) and grid[i][j]:\n        grid[i][j] = 0\n        for di, dj in ((0,1),(0,-1),(1,0),(-1,0)):\n            dfs(i+di, j+dj)\ncount = 0\nfor i in range(len(grid)):\n    for j in range(len(grid[0])):\n        if grid[i][j]:\n            dfs(i, j)\n            count += 1\nprint(count)"}, Reward: 550, Difficulty: 3, Grade: 11},
	{ID: "py10-4", Title: "Архив анаграмм", Description: "Дан список слов. Сгруппируйте анаграммы. Выведите каждую группу на новой строке.", Language: "python", StarterCode: "words = input().split()\n# ваш код", AcceptedAnswers: []string{"from collections import defaultdict\ngroups = defaultdict(list)\nfor w in words:\n    groups[''.join(sorted(w))].append(w)\nfor g in groups.values():\n    print(*g)"}, Reward: 420, Difficulty: 2, Grade: 11},
	{ID: "py10-5", Title: "Максимальный заряд", Description: "Дан массив чисел. Найдите максимальную сумму непрерывного подотрезка (алгоритм Кадане).", Language: "python", StarterCode: "nums = list(map(int, input().split()))\n# ваш код", AcceptedAnswers: []string{"mx = cur = nums[0]\nfor x in nums[1:]:\n    cur = max(x, cur + x)\n    mx = max(mx, cur)\nprint(mx)"}, Reward: 400, Difficulty: 2, Grade: 11},
	{ID: "py10-6", Title: "Баланс двух модулей", Description: "Даны времена задач. Распределите их между двумя модулями с минимальной разницей сумм. Выведите разницу.", Language: "python", StarterCode: "times = list(map(int, input().split()))\n# ваш код", AcceptedAnswers: []string{"total = sum(times)\ndp = {0}\nfor t in times:\n    dp |= {x + t for x in dp}\nprint(min(abs(total - 2*s) for s in dp))"}, Reward: 600, Difficulty: 3, Grade: 11},
	{ID: "py10-7", Title: "Порядок запуска", Description: "Дан граф зависимостей (список пар «от кого зависит»). Выведите возможный порядок запуска систем.", Language: "python", StarterCode: "from collections import deque\ndef topo_sort(n, edges):\n    indeg = [0]*n\n    g = [[] for _ in range(n)]\n    for u, v in edges:\n        g[u].append(v)\n        indeg[v] += 1\n    q = deque([i for i in range(n) if indeg[i] == 0])\n    res = []\n    while q:\n        u = q.popleft()\n        res.append(u)\n        for v in g[u]:\n            indeg[v] -= 1\n            if indeg[v] == 0:\n                q.append(v)\n    return res if len(res) == n else []", AcceptedAnswers: []string{}, Reward: 550, Difficulty: 3, Grade: 11},
	{ID: "py10-8", Title: "Обнаружение цикла", Description: "Дан ориентированный граф. Определите, есть ли в нём цикл.", Language: "python", StarterCode: "n = int(input())\nedges = []\nwhile True:\n    try:\n        u, v = map(int, input().split())\n        edges.append((u, v))\n    except: break\n# ваш код", AcceptedAnswers: []string{"from collections import defaultdict\ng = defaultdict(list)\nfor u, v in edges:\n    g[u].append(v)\nvisited = [0]*n\ndef dfs(u):\n    visited[u] = 1\n    for v in g[u]:\n        if visited[v] == 1: return True\n        if visited[v] == 0 and dfs(v): return True\n    visited[u] = 2\n    return False\nprint('YES' if any(dfs(i) for i in range(n) if visited[i] == 0) else 'NO')"}, Reward: 500, Difficulty: 3, Grade: 11},
	{ID: "py10-9", Title: "Связность базы", Description: "Дан неориентированный граф. Определите, связен ли он (из любой вершины можно добраться в любую).", Language: "python", StarterCode: "n = int(input())\nedges = []\nwhile True:\n    try:\n        u, v = map(int, input().split())\n        edges.append((u, v))\n    except: break\n# ваш код", AcceptedAnswers: []string{"g = [[] for _ in range(n)]\nfor u, v in edges:\n    g[u].append(v)\n    g[v].append(u)\nvisited = [False]*n\ndef dfs(u):\n    visited[u] = True\n    for v in g[u]:\n        if not visited[v]: dfs(v)\ndfs(0)\nprint('YES' if all(visited) else 'NO')"}, Reward: 400, Difficulty: 2, Grade: 11},
	{ID: "py10-11", Title: "Минимальное окно", Description: "Дана строка s и набор символов t. Найдите минимальную подстроку s, содержащую все символы t.", Language: "python", StarterCode: "s, t = input().split()\n# ваш код", AcceptedAnswers: []string{"from collections import Counter\nneed = Counter(t)\nmissing = len(t)\nleft = start = end = 0\nres = ''\nfor right, c in enumerate(s):\n    if need[c] > 0: missing -= 1\n    need[c] -= 1\n    if missing == 0:\n        while need[s[left]] < 0:\n            need[s[left]] += 1\n            left += 1\n        if not res or right - left < end - start:\n            start, end = left, right\n            res = s[left:right+1]\n        need[s[left]] += 1\n        missing += 1\n        left += 1\nprint(res)"}, Reward: 650, Difficulty: 3, Grade: 11},
	{ID: "py10-12", Title: "Маршруты по сетке", Description: "Робот движется только вправо или вниз. Есть заблокированные клетки. Посчитайте число путей.", Language: "python", StarterCode: "n, m = map(int, input().split())\ngrid = [list(map(int, input().split())) for _ in range(n)]\n# ваш код", AcceptedAnswers: []string{"dp = [[0]*m for _ in range(n)]\nif grid[0][0]: dp[0][0] = 1\nfor i in range(n):\n    for j in range(m):\n        if grid[i][j] and not (i == 0 and j == 0):\n            dp[i][j] = (dp[i-1][j] if i else 0) + (dp[i][j-1] if j else 0)\nprint(dp[-1][-1])"}, Reward: 500, Difficulty: 2, Grade: 11},
	{ID: "py10-13", Title: "Груз артефактов", Description: "Даны веса и ценности артефактов, а также вместимость корабля. Найдите максимальную ценность.", Language: "python", StarterCode: "n, W = map(int, input().split())\nitems = [tuple(map(int, input().split())) for _ in range(n)]\n# ваш код", AcceptedAnswers: []string{"dp = [0]*(W+1)\nfor w, v in items:\n    for cap in range(W, w-1, -1):\n        dp[cap] = max(dp[cap], dp[cap-w] + v)\nprint(dp[W])"}, Reward: 600, Difficulty: 3, Grade: 11},
	{ID: "py10-17", Title: "Слияние интервалов", Description: "Дан список интервалов активности команд. Объедините пересекающиеся интервалы.", Language: "python", StarterCode: "intervals = eval(input())\n# ваш код", AcceptedAnswers: []string{"intervals.sort()\nmerged = []\nfor s, e in intervals:\n    if not merged or merged[-1][1] < s:\n        merged.append([s, e])\n    else:\n        merged[-1][1] = max(merged[-1][1], e)\nprint(merged)"}, Reward: 420, Difficulty: 2, Grade: 11},
	{ID: "py10-19", Title: "Минимум прыжков", Description: "a[i] — максимальная длина прыжка из позиции i. Найдите минимум прыжков до конца массива.", Language: "python", StarterCode: "a = list(map(int, input().split()))\n# ваш код", AcceptedAnswers: []string{"jumps = 0\ncur_end = 0\nfarthest = 0\nfor i in range(len(a)-1):\n    farthest = max(farthest, i + a[i])\n    if i == cur_end:\n        jumps += 1\n        cur_end = farthest\nprint(jumps)"}, Reward: 500, Difficulty: 3, Grade: 11},
	{ID: "py10-20", Title: "Изоморфные коды", Description: "Даны строки s и t. Определите, можно ли однозначно заменить символы s, чтобы получить t.", Language: "python", StarterCode: "s, t = input().split()\n# ваш код", AcceptedAnswers: []string{"m1, m2 = {}, {}\nfor a, b in zip(s, t):\n    if (a in m1 and m1[a] != b) or (b in m2 and m2[b] != a):\n        print('NO')\n        break\n    m1[a] = b\n    m2[b] = a\nelse: print('YES')"}, Reward: 450, Difficulty: 2, Grade: 11},
}

func All() []models.Question { return append([]models.Question(nil), bank...) }
func ForGrade(grade int) []models.Question {
	if grade < 9 || grade > 11 {
		return All()
	}
	out := make([]models.Question, 0)
	for _, q := range bank {
		if q.Grade == grade {
			out = append(out, q)
		}
	}
	return out
}
func Tasks() []models.TerminalTask { return append([]models.TerminalTask(nil), tasks...) }
func TasksForGrade(grade int) []models.TerminalTask {
	out := make([]models.TerminalTask, 0)
	for _, t := range tasks {
		if t.Grade == grade || t.Grade == 0 {
			out = append(out, t)
		}
	}
	return out
}